from fastapi import APIRouter, HTTPException, Path
from starlette import status
from app.models.project import Projects
from app.schemas.project import CreateProjectRequest, ProjectResponse, UpdateProjectRequest
from app.dependencies.auth import user_dependency
from app.database.database import db_dependency

router = APIRouter(prefix = '/projects' , tags = ['projects'])


@router.get('/', status_code=status.HTTP_200_OK)
async def get_all_projects(current_user : user_dependency, db: db_dependency):
    projects = db.query(Projects).filter(Projects.owner_id == current_user.id).all()
    return projects


@router.post('/', status_code=status.HTTP_201_CREATED)
async def create_project(current_user : user_dependency, db: db_dependency, project_request: CreateProjectRequest):
    new_project = Projects(**project_request.model_dump(), owner_id = current_user.id )
    db.add(new_project)
    db.commit()
    db.refresh(new_project)  # Populates autogenerated fields (like id)
    return new_project


@router.get("/{project_id}", response_model=ProjectResponse)
async def get_project_by_id(db: db_dependency, current_user: user_dependency,project_id : int = Path(gt=0)):
    project = db.query(Projects).filter(Projects.owner_id == current_user.id, Projects.id == project_id).first()
    if not project:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, 
                            detail=f'Project with ID {project_id} not found')
    return project


@router.delete("/{project_id}")
async def remove_project(db: db_dependency, current_user: user_dependency, project_id : int = Path(gt=0)):
    project = db.query(Projects).filter(Projects.id == project_id , Projects.owner_id == current_user.id).first()
    if not project:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Project with ID {project_id} not found")
    db.delete(project)
    db.commit()
    
    
    
# update project
@router.patch('/{project_id}')
async def update_project(db:db_dependency, current_user: user_dependency, project_update: UpdateProjectRequest, project_id : int = Path(gt=0)):
    project = db.query(Projects).filter(Projects.owner_id == current_user.id , Projects.id == project_id).first()
    if not project:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Project with ID {project_id} not found")
    update_data = project_update.model_dump(exclude_unset=True)
    for key, value in update_data.items():
        setattr(project, key, value)
    db.commit()
    db.refresh(project)
    return project

        
    
     